[server]
host: 0.0.0.0

[file_manager]
enable_object_processing: True

[authorization]
trusted_clients:
    100.0.0.0/8
    10.10.10.0/24
    10.10.9.0/24
    127.0.0.0/8

cors_domains:
    *.echo-magellanic.ts.net
    *.local
    *.local:7136

[history]

[octoprint_compat]

[job_queue]
automatic_transition: False

[power tasmota_plug]
type: tasmota
address: 10.10.5.50

[update_manager]
enable_auto_refresh: True

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail
persistent_files: config.json

[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition.git
virtualenv: ~/.KlipperScreen-env
requirements: scripts/KlipperScreen-requirements.txt
system_dependencies: scripts/system-dependencies.json
managed_services: KlipperScreen

[update_manager client klipper-config]
type: git_repo
path: ~/config
origin: https://github.com/retsamedoc/VoronV2_klipper.git
primary_branch: main
is_system_service: False

[update_manager klipper-led_effect]
type: git_repo
path: ~/klipper-led_effect
origin: https://github.com/julianschill/klipper-led_effect.git
is_system_service: False

[update_manager klipper-virtual_leds]
type: git_repo
path: ~/klipper-virtual_leds
origin: https://github.com/MapleLeafMakers/klipper-virtual_leds.git
is_system_service: False

[update_manager klipper-tmc_autotune]
type: git_repo
channel: dev
path: ~/klipper_tmc_autotune
origin: https://github.com/andrewmcgr/klipper_tmc_autotune.git
managed_services: klipper
primary_branch: main
install_script: install.sh

[update_manager klipper_auto_speed]
type: git_repo
path: ~/klipper_auto_speed
origin: https://github.com/anonoei/klipper_auto_speed.git
primary_branch: main
install_script: install.sh
managed_services: klipper

[update_manager voron-klipper-extensions]
type: git_repo
path: ~/voron-klipper-extensions
origin: https://github.com/voidtrance/voron-klipper-extensions.git
install_script: install-extensions.sh
managed_services: klipper

## Klippain Shake&Tune automatic update management
[update_manager Klippain-ShakeTune]
type: git_repo
origin: https://github.com/Frix-x/klippain-shaketune.git
path: ~/klippain-shaketune
virtualenv: ~/klippy-env
requirements: requirements.txt
system_dependencies: system-dependencies.json
primary_branch: main
managed_services: klipper

[update_manager client PrettyGCode]
type: git_repo
path: ~/pgcode
origin: https://github.com/Kragrathea/pgcode.git
primary_branch: main
is_system_service: False

[update_manager virtual_leds]
type: git_repo
path: ~/klipper-virtual_leds
origin: https://github.com/MapleLeafMakers/klipper-virtual_leds.git
is_system_service: False
primary_branch: main

[mqtt]
address: 10.10.10.10
port: 1883
username: {secrets.mqtt_credentials.username}
password: {secrets.mqtt_credentials.password}
mqtt_protocol: v3.1.1
enable_moonraker_api: True
publish_split_status: True
status_objects:
  webhooks
  toolhead=position,homed_axes,extruder
  extruder=temperature, target, power
  heater_bed=temperature, target, power
  fan=speed, rpm
  print_stats: state, print_duration, filament_used, filename, info
  virtual_sdcard: progress
  temperature_sensor chamber; temperature
instance_name: printer/V2_823
default_qos: 0

[update_manager Katapult]
type: git_repo
path: ~/katapult
origin: https://github.com/Arksine/katapult.git
is_system_service: False

[update_manager happy-hare]
type: git_repo
path: ~/Happy-Hare
origin: https://github.com/moggieuk/Happy-Hare.git
primary_branch: main
install_script: install.sh
managed_services: klipper

[mmu_server]
enable_file_preprocessor: True
enable_toolchange_next_pos: True
update_spoolman_location: True

